-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, A.PRICE
FROM 
FOOD_PRODUCT A JOIN (SELECT MAX(PRICE) PRICE 
                      FROM FOOD_PRODUCT
                     ) B
ON A.PRICE = B.PRICE